version: '3.3'
services:
  nginx:
    image: nginx
    container_name: container-nginx
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    ports:
      - "8080:80"
    volumes:
      # Arquivo de configuração
      - ./mysite.template:/etc/nginx/
      # Dados
      - ./src:/var/www

  web:
    image: nginx
    container_name: container-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    command: [nginx-debug, '-g', 'daemon off;']
